# theme: jekyll-theme-minimal
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Web Exercise 1 - Introduction to GitHub and Online Data Science Resources
description: GitHub Pages website created for BDA 594
